name: My ProductPage & PublicCode Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create a Product Page
        uses: OpenCatalogi/productpage-action@latest
        with:
          nl_design_theme_classname: "open-webconcept-theme"
          start_page: 'https://github.com/CommonGateway/CustomerInteractionBundle/blob/main/README.md'
          jumbotron_image_placement: "right"
          jumbotron_image_url: "https://raw.githubusercontent.com/CommonGateway/CustomerInteractionBundle/main/docs/klanten.svg"
          github_api_base_url: https://api.github.com/repos/CommonGateway/CustomerInteractionBundle/contents
          favicon_url: https://openwebconcept.nl/wp-content/uploads/2019/07/cropped-Favicon-32x32.png
      - name: Create or Update publiccode.yaml
        uses: OpenCatalogi/publiccode-action@latest
